use crate::parse;
use crate::sidecar::{resolve_model, SidecarConfig};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const BEGIN_MARKER: &str = "# BEGIN forge-council agents";
const END_MARKER: &str = "# END forge-council agents";

pub struct RenderResult {
    pub agents_dir: PathBuf,
    pub config_file: PathBuf,
}

pub fn render_codex_agent_config(
    module_root: &Path,
    codex_root: &Path,
) -> Result<RenderResult, String> {
    let agents_src = module_root.join("agents");
    if !agents_src.is_dir() {
        return Err(format!(
            "agents directory not found at {}",
            agents_src.display()
        ));
    }

    let defaults_path = module_root.join("defaults.yaml");
    if !defaults_path.is_file() {
        return Err(format!(
            "defaults file not found at {}",
            defaults_path.display()
        ));
    }

    let codex_agents_dir = codex_root.join("agents");
    fs::create_dir_all(&codex_agents_dir)
        .map_err(|e| format!("failed to create {}: {e}", codex_agents_dir.display()))?;

    cleanup_legacy_files(&codex_agents_dir)?;

    let config = SidecarConfig::load(module_root);
    let global_tiers = config.global_tiers();
    let codex_tiers = config.provider_tiers("codex");

    let mut files: Vec<_> = fs::read_dir(&agents_src)
        .map_err(|e| format!("failed to read {}: {e}", agents_src.display()))?
        .filter_map(Result::ok)
        .filter(|entry| entry.path().extension().is_some_and(|ext| ext == "md"))
        .collect();
    files.sort_by_key(fs::DirEntry::file_name);

    let mut block = String::new();
    block.push_str("# Generated by forge-lib install-codex-agent-config\n");
    block.push_str("# Do not edit manually.\n");

    for entry in files {
        let source_path = entry.path();
        let agent_name = source_path
            .file_stem()
            .and_then(|s| s.to_str())
            .ok_or_else(|| format!("invalid agent filename: {}", source_path.display()))?
            .to_string();

        let source_file = fs::read_to_string(&source_path)
            .map_err(|e| format!("failed to read {}: {e}", source_path.display()))?;

        let description = parse::fm_value(&source_file, "description")
            .or_else(|| parse::fm_value(&source_file, "claude.description"))
            .ok_or_else(|| format!("missing description in {}", source_path.display()))?;

        let model_tier = config
            .agent_value(&agent_name, "model")
            .or_else(|| parse::fm_value(&source_file, "claude.model"))
            .ok_or_else(|| format!("could not resolve model tier for agent {agent_name}"))?;

        let model = resolve_model(&model_tier, &global_tiers, &codex_tiers);
        let effort = resolve_reasoning_effort(&model_tier, &model);

        let mut role_toml = String::new();
        role_toml.push_str("# Generated by forge-lib install-codex-agent-config\n");
        role_toml.push_str("# Source: agents/");
        role_toml.push_str(&agent_name);
        role_toml.push_str(".md\n");
        let _ = writeln!(role_toml, "description = \"{}\"", toml_escape(&description));
        let _ = writeln!(role_toml, "model = \"{}\"", toml_escape(&model));
        let _ = writeln!(
            role_toml,
            "model_reasoning_effort = \"{}\"",
            toml_escape(effort)
        );
        let _ = writeln!(
            role_toml,
            "prompt_file = \"{}\"",
            toml_escape(&format!("{agent_name}.md"))
        );

        let role_path = codex_agents_dir.join(format!("{agent_name}.toml"));
        fs::write(&role_path, role_toml)
            .map_err(|e| format!("failed to write {}: {e}", role_path.display()))?;

        let _ = writeln!(block, "\n[agents.{agent_name}]");
        let _ = writeln!(block, "description = \"{}\"", toml_escape(&description));
        let _ = writeln!(
            block,
            "config_file = \"agents/{}.toml\"",
            toml_escape(&agent_name)
        );
    }

    let codex_config = codex_root.join("config.toml");
    let existing = fs::read_to_string(&codex_config).unwrap_or_default();
    let stripped = strip_managed_block(&existing, BEGIN_MARKER, END_MARKER);

    let mut rendered = String::new();
    if !stripped.is_empty() {
        rendered.push_str(&stripped);
        if !stripped.ends_with('\n') {
            rendered.push('\n');
        }
        rendered.push('\n');
    }
    rendered.push_str(BEGIN_MARKER);
    rendered.push('\n');
    rendered.push_str(&block);
    if !block.ends_with('\n') {
        rendered.push('\n');
    }
    rendered.push_str(END_MARKER);
    rendered.push('\n');

    fs::write(&codex_config, rendered)
        .map_err(|e| format!("failed to write {}: {e}", codex_config.display()))?;

    Ok(RenderResult {
        agents_dir: codex_agents_dir,
        config_file: codex_config,
    })
}

fn cleanup_legacy_files(codex_agents_dir: &Path) -> Result<(), String> {
    let legacy_manifest = codex_agents_dir.join("forge-council-agents.toml");
    if legacy_manifest.exists() {
        fs::remove_file(&legacy_manifest)
            .map_err(|e| format!("failed to remove {}: {e}", legacy_manifest.display()))?;
    }

    for entry in fs::read_dir(codex_agents_dir)
        .map_err(|e| format!("failed to read {}: {e}", codex_agents_dir.display()))?
    {
        let entry = entry.map_err(|e| format!("failed to read directory entry: {e}"))?;
        let path = entry.path();
        let is_prompt = path
            .file_name()
            .and_then(|n| n.to_str())
            .is_some_and(|name| name.ends_with(".prompt.md"));
        if is_prompt {
            fs::remove_file(&path)
                .map_err(|e| format!("failed to remove {}: {e}", path.display()))?;
        }
    }

    Ok(())
}

fn strip_managed_block(content: &str, begin: &str, end: &str) -> String {
    let mut output = String::new();
    let mut skip = false;
    for line in content.lines() {
        if line == begin {
            skip = true;
            continue;
        }
        if line == end {
            skip = false;
            continue;
        }
        if !skip {
            output.push_str(line);
            output.push('\n');
        }
    }
    output.trim_end_matches('\n').to_string()
}

fn toml_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn resolve_reasoning_effort(tier: &str, model: &str) -> &'static str {
    if tier == "fast" {
        "low"
    } else if tier == "strong" {
        if model.contains("-max") {
            "high"
        } else {
            "medium"
        }
    } else {
        "medium"
    }
}

#[cfg(test)]
mod tests;
